In [4]:
#importing required libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

In [5]:
df1 = pd.read_csv('/content/train_wn75k28 (1).csv')
df1

id  created_at  campaign_var_1  campaign_var_2  products_purchased  \
0          1  2021-01-01               1               2                 2.0   
1          2  2021-01-01               2               1                 2.0   
2          3  2021-01-01               9               3                 3.0   
3          4  2021-01-01               6               7                 2.0   
4          5  2021-01-01               4               6                 NaN   
...      ...         ...             ...             ...                 ...   
39156  39157  2021-12-31              11              11                 2.0   
39157  39158  2021-12-31               3               9                 3.0   
39158  39159  2021-12-31               8               7                 2.0   
39159  39160  2021-12-31               7              12                 2.0   
39160  39161  2021-12-31               2               5                 NaN   

      signup_date  user_activity_var_1  user_activity_var_2  \
0      2020-09-24                    0                    0   
1      2020-09-19                    1                    0   
2      2021-08-11                    1                    0   
3      2017-10-04                    0                    0   
4      2020-06-08                    0                    0   
...           ...                  ...                  ...   
39156  2017-10-19                    1                    0   
39157         NaN                    0                    0   
39158         NaN                    1                    0   
39159         NaN                    0                    0   
39160  2019-08-11                    1                    0   

       user_activity_var_3  user_activity_var_4  user_activity_var_5  \
0                        0                    0                    0   
1                        1                    0                    0   
2                        0                    0                    0   
3                        0                    0                    0   
4                        0                    0                    0   
...                    ...                  ...                  ...   
39156                    0                    0                    1   
39157                    0                    0                    0   
39158                    0                    0                    1   
39159                    0                    0                    0   
39160                    0                    0                    0   

       user_activity_var_6  user_activity_var_7  user_activity_var_8  \
0                        0                    1                    1   
1                        0                    1                    0   
2                        0                    0                    0   
3                        0                    0                    0   
4                        0                    1                    0   
...                    ...                  ...                  ...   
39156                    1                    1                    0   
39157                    0                    0                    0   
39158                    0                    1                    0   
39159                    1                    0                    0   
39160                    0                    1                    0   

       user_activity_var_9  user_activity_var_10  user_activity_var_11  \
0                        0                     0                     0   
1                        0                     0                     0   
2                        0                     0                     0   
3                        0                     0                     0   
4                        0                     0                     1   
...                    ...                   ...                   ...   
39156                    0                  

In [6]:
df1.drop(['id','created_at','signup_date'], axis=1, inplace=True)

In [23]:
df1.size

626576

In [7]:
df1.isnull().sum()

campaign_var_1              0
campaign_var_2              0
products_purchased      20911
user_activity_var_1         0
user_activity_var_2         0
user_activity_var_3         0
user_activity_var_4         0
user_activity_var_5         0
user_activity_var_6         0
user_activity_var_7         0
user_activity_var_8         0
user_activity_var_9         0
user_activity_var_10        0
user_activity_var_11        0
user_activity_var_12        0
buy                         0
dtype: int64

In [8]:
df1.columns

Index(['campaign_var_1', 'campaign_var_2', 'products_purchased',
       'user_activity_var_1', 'user_activity_var_2', 'user_activity_var_3',
       'user_activity_var_4', 'user_activity_var_5', 'user_activity_var_6',
       'user_activity_var_7', 'user_activity_var_8', 'user_activity_var_9',
       'user_activity_var_10', 'user_activity_var_11', 'user_activity_var_12',
       'buy'],
      dtype='object')

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39161 entries, 0 to 39160
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   campaign_var_1        39161 non-null  int64  
 1   campaign_var_2        39161 non-null  int64  
 2   products_purchased    18250 non-null  float64
 3   user_activity_var_1   39161 non-null  int64  
 4   user_activity_var_2   39161 non-null  int64  
 5   user_activity_var_3   39161 non-null  int64  
 6   user_activity_var_4   39161 non-null  int64  
 7   user_activity_var_5   39161 non-null  int64  
 8   user_activity_var_6   39161 non-null  int64  
 9   user_activity_var_7   39161 non-null  int64  
 10  user_activity_var_8   39161 non-null  int64  
 11  user_activity_var_9   39161 non-null  int64  
 12  user_activity_var_10  39161 non-null  int64  
 13  user_activity_var_11  39161 non-null  int64  
 14  user_activity_var_12  39161 non-null  int64  
 15  buy                

In [8]:
df1.describe()

campaign_var_1  campaign_var_2  products_purchased  \
count    39161.000000    39161.000000        18250.000000   
mean         6.523812        6.452746            2.154137   
std          3.472944        2.614296            0.779815   
min          1.000000        1.000000            1.000000   
25%          4.000000        5.000000            2.000000   
50%          6.000000        6.000000            2.000000   
75%          9.000000        8.000000            3.000000   
max         16.000000       15.000000            4.000000   

       user_activity_var_1  user_activity_var_2  user_activity_var_3  \
count         39161.000000         39161.000000         39161.000000   
mean              0.400092             0.006716             0.102832   
std               0.509194             0.081676             0.303743   
min               0.000000             0.000000             0.000000   
25%               0.000000             0.000000             0.000000   
50%               0.000000             0.000000             0.000000   
75%               1.000000             0.000000             0.000000   
max               3.000000             1.000000             1.000000   

       user_activity_var_4  user_activity_var_5  user_activity_var_6  \
count         39161.000000         39161.000000         39161.000000   
mean              0.011465             0.151503             0.499834   
std               0.106463             0.359681             0.558166   
min               0.000000             0.000000             0.000000   
25%               0.000000             0.000000             0.000000   
50%               0.000000             0.000000             0.000000   
75%               0.000000             0.000000             1.000000   
max               1.000000             2.000000             3.000000   

       user_activity_var_7  user_activity_var_8  user_activity_var_9  \
count         39161.000000         39161.000000         39161.000000   
mean              0.286612             0.174434             0.011440   
std               0.455784             0.379689             0.106346   
min               0.000000             0.000000             0.000000   
25%               0.000000             0.000000             0.000000   
50%               0.000000             0.000000             0.000000   
75%               1.000000             0.000000             0.000000   
max               2.000000             2.000000             1.000000   

       user_activity_var_10  user_activity_var_11  user_activity_var_12  \
count          39161.000000          39161.000000          39161.000000   
mean               0.000383              0.218942              0.000562   
std                0.019568              0.431544              0.023696   
min                0.000000              0.000000              0.000000   
25%                0.000000              0.000000              0.000000   
50%                0.000000              0.000000              0.000000   
75%                0.000000              0.000000              0.000000   
max                1.000000              4.000000              1.000000   

                buy  
count  39161.000000  
mean       0.051020  
std        0.220042  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [9]:
df1.isnull().sum()

campaign_var_1              0
campaign_var_2              0
products_purchased      20911
user_activity_var_1         0
user_activity_var_2         0
user_activity_var_3         0
user_activity_var_4         0
user_activity_var_5         0
user_activity_var_6         0
user_activity_var_7         0
user_activity_var_8         0
user_activity_var_9         0
user_activity_var_10        0
user_activity_var_11        0
user_activity_var_12        0
buy                         0
dtype: int64

In [10]:
# replacing missing values 
df1['products_purchased'] = df1['products_purchased'].fillna(df1['products_purchased'].median())


In [11]:
df1.tail()

campaign_var_1  campaign_var_2  products_purchased  \
39156              11              11                 2.0   
39157               3               9                 3.0   
39158               8               7                 2.0   
39159               7              12                 2.0   
39160               2               5                 2.0   

       user_activity_var_1  user_activity_var_2  user_activity_var_3  \
39156                    1                    0                    0   
39157                    0                    0                    0   
39158                    1                    0                    0   
39159                    0                    0                    0   
39160                    1                    0                    0   

       user_activity_var_4  user_activity_var_5  user_activity_var_6  \
39156                    0                    1                    1   
39157                    0                    0                    0   
39158                    0                    1                    0   
39159                    0                    0                    1   
39160                    0                    0                    0   

       user_activity_var_7  user_activity_var_8  user_activity_var_9  \
39156                    1                    0                    0   
39157                    0                    0                    0   
39158                    1                    0                    0   
39159                    0                    0                    0   
39160                    1                    0                    0   

       user_activity_var_10  user_activity_var_11  user_activity_var_12  buy  
39156                     0                     0                     0    0  
39157                     0                     0                     0    0  
39158                     0                     0                     0    0  
39159                     0                     1                     0    0  
39160                     0                     0                     0    0

In [12]:
df1.isnull().sum()

campaign_var_1          0
campaign_var_2          0
products_purchased      0
user_activity_var_1     0
user_activity_var_2     0
user_activity_var_3     0
user_activity_var_4     0
user_activity_var_5     0
user_activity_var_6     0
user_activity_var_7     0
user_activity_var_8     0
user_activity_var_9     0
user_activity_var_10    0
user_activity_var_11    0
user_activity_var_12    0
buy                     0
dtype: int64

In [13]:
#. Putting Feature Variable to X and Target variable to y.

x = df1.drop(['buy'], axis=1)
y = df1[['buy']] #output feature


In [14]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=33b70482fc315713f318bccad7d359683789bd78cd63b70c9b276f7baaa50315
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [15]:
#   Train-Test-Split is performed

from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.8, random_state=42, stratify=y)
x_train.shape, x_test.shape # strity used because data is imbalanced.. so stratify will balance for training..

((31328, 15), (7833, 15))

In [54]:
# Let’s import RandomForestClassifier and fit the data.
from sklearn.ensemble import RandomForestClassifier


In [59]:
# model building
forest = RandomForestClassifier() # base model


In [60]:
# model fitting
forest.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier()

In [62]:
# predict train results
y_pred_train = forest.predict(x_train)

In [63]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

print('Training accuracy is', accuracy_score(y_train, y_pred_train)*100)
print('-------------------------------------------------------')
print('Confusion Matrix for training data is \n', confusion_matrix(y_train, y_pred_train))
print('-------------------------------------------------------')
print('Classification report for training data \n', (classification_report(y_train, y_pred_train)))
print('=======================================================')
print("f1 score for base model is : " , f1_score(y_train, y_pred_train))
print('-------------------------------------------------------')


Training accuracy is 98.39121552604698
-------------------------------------------------------
Confusion Matrix for training data is 
 [[29709    21]
 [  483  1115]]
-------------------------------------------------------
Classification report for training data 
               precision    recall  f1-score   support

           0       0.98      1.00      0.99     29730
           1       0.98      0.70      0.82      1598

    accuracy                           0.98     31328
   macro avg       0.98      0.85      0.90     31328
weighted avg       0.98      0.98      0.98     31328

f1 score for base model is :  0.8156547183613753
-------------------------------------------------------


In [64]:
# predict test results
y_pred_test = forest.predict(x_test)

In [65]:
print('Validation accuracy is', accuracy_score(y_test, y_pred_test))
print('-------------------------------------------------------')
print('Confusion Matrix for Validation data is \n', confusion_matrix(y_test, y_pred_test))
print('-------------------------------------------------------')
print('Classification report for Validation data \n', (classification_report(y_test, y_pred_test)))
print('=======================================================')
print("f1 score for validation model is : " , f1_score(y_test, y_pred_test))
print('-------------------------------------------------------')


Validation accuracy is 0.972935018511426
-------------------------------------------------------
Confusion Matrix for Validation data is 
 [[7403   30]
 [ 182  218]]
-------------------------------------------------------
Classification report for Validation data 
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      7433
           1       0.88      0.55      0.67       400

    accuracy                           0.97      7833
   macro avg       0.93      0.77      0.83      7833
weighted avg       0.97      0.97      0.97      7833

f1 score for validation model is :  0.6728395061728396
-------------------------------------------------------


# Validation data

In [29]:
df2 = pd.read_csv('/content/test_Wf7sxXF (1).csv')

In [30]:
df2.tail()

id  created_at  campaign_var_1  campaign_var_2  products_purchased  \
13179  52341  2022-03-30              16              12                 NaN   
13180  52342  2022-03-30              12               8                 NaN   
13181  52343  2022-03-30              14              14                 3.0   
13182  52344  2022-03-30              14              10                 NaN   
13183  52345  2022-03-30              13              13                 NaN   

      signup_date  user_activity_var_1  user_activity_var_2  \
13179         NaN                    0                    0   
13180  2022-03-19                    1                    0   
13181  2021-08-15                    0                    0   
13182         NaN                    0                    0   
13183         NaN                    0                    0   

       user_activity_var_3  user_activity_var_4  user_activity_var_5  \
13179                    0                    0                    0   
13180                    0                    0                    0   
13181                    1                    0                    0   
13182                    0                    0                    0   
13183                    0                    0                    0   

       user_activity_var_6  user_activity_var_7  user_activity_var_8  \
13179                    1                    1                    0   
13180                    1                    0                    0   
13181                    0                    1                    0   
13182                    0                    1                    0   
13183                    1                    1                    1   

       user_activity_var_9  user_activity_var_10  user_activity_var_11  \
13179                    0                     0                     0   
13180                    0                     0                     0   
13181                    0                     0                     0   
13182                    0                     0                     1   
13183                    0                     0                     1   

       user_activity_var_12  
13179                     0  
13180                     0  
13181                     0  
13182                     0  
13183                     0

In [31]:
df2.drop(['id','created_at','signup_date'], axis=1, inplace=True)

In [32]:
df2.isnull().sum()

campaign_var_1             0
campaign_var_2             0
products_purchased      8136
user_activity_var_1        0
user_activity_var_2        0
user_activity_var_3        0
user_activity_var_4        0
user_activity_var_5        0
user_activity_var_6        0
user_activity_var_7        0
user_activity_var_8        0
user_activity_var_9        0
user_activity_var_10       0
user_activity_var_11       0
user_activity_var_12       0
dtype: int64

In [33]:
df2['products_purchased'] = df2['products_purchased'].fillna(df2['products_purchased'].median())

In [34]:
df2.isnull().sum()

campaign_var_1          0
campaign_var_2          0
products_purchased      0
user_activity_var_1     0
user_activity_var_2     0
user_activity_var_3     0
user_activity_var_4     0
user_activity_var_5     0
user_activity_var_6     0
user_activity_var_7     0
user_activity_var_8     0
user_activity_var_9     0
user_activity_var_10    0
user_activity_var_11    0
user_activity_var_12    0
dtype: int64

In [73]:
df2.columns==x_test.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [74]:
final_y_test = forest.predict(df2)

In [75]:
final_y_test

array([1, 0, 0, ..., 0, 0, 0])

In [76]:
y_test = pd.DataFrame(final_y_test)

In [77]:
y_test.value_counts()

0    12806
1      378
dtype: int64

# case 2 => Hyperparameter Tuning/Model Improvement

In [79]:
forest_tune = RandomForestClassifier()

In [80]:
param_grid = [{'bootstrap': [True], 'max_depth': [5, 10, None], 'max_features': ['auto', 'log2'], 'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]}]


In [83]:
from sklearn.model_selection import GridSearchCV
rfgrid = GridSearchCV(forest, param_grid=param_grid, cv=2, verbose=True, n_jobs=-1)

In [84]:
best_rf = rfgrid.fit(x_train, y_train)

Fitting 2 folds for each of 60 candidates, totalling 120 fits


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


In [85]:
best_rf.best_estimator_

RandomForestClassifier(max_depth=10, max_features='log2', n_estimators=9)

In [87]:
# 1. Predict Training Results
y_pred_train = rfgrid.predict(x_train)


In [88]:
print('Training accuracy is', accuracy_score(y_train, y_pred_train)*100)
print('-------------------------------------------------------')
print('Confusion Matrix for training data is \n', confusion_matrix(y_train, y_pred_train))
print('-------------------------------------------------------')
print('Classification report for training data \n', (classification_report(y_train, y_pred_train)))
print('=======================================================')
print("f1 score for base model is : " , f1_score(y_train, y_pred_train))
print('-------------------------------------------------------')


Training accuracy is 97.57086312563841
-------------------------------------------------------
Confusion Matrix for training data is 
 [[29711    19]
 [  742   856]]
-------------------------------------------------------
Classification report for training data 
               precision    recall  f1-score   support

           0       0.98      1.00      0.99     29730
           1       0.98      0.54      0.69      1598

    accuracy                           0.98     31328
   macro avg       0.98      0.77      0.84     31328
weighted avg       0.98      0.98      0.97     31328

f1 score for base model is :  0.6922765871411243
-------------------------------------------------------


In [93]:
# 2. Predict Validation Results
y_pred_val = rfgrid.predict(df2)


In [94]:
print('Validation accuracy is', accuracy_score(y_test, y_pred_val))
print('-------------------------------------------------------')
print('Confusion Matrix for Validation data is \n', confusion_matrix(y_test, y_pred_val))
print('-------------------------------------------------------')
print('Classification report for Validation data \n', (classification_report(y_test, y_pred_val)))
print('=======================================================')
print("f1 score for validation model is : " , f1_score(y_test, y_pred_val))
print('-------------------------------------------------------')


Validation accuracy is 0.9939320388349514
-------------------------------------------------------
Confusion Matrix for Validation data is 
 [[12802     4]
 [   76   302]]
-------------------------------------------------------
Classification report for Validation data 
               precision    recall  f1-score   support

           0       0.99      1.00      1.00     12806
           1       0.99      0.80      0.88       378

    accuracy                           0.99     13184
   macro avg       0.99      0.90      0.94     13184
weighted avg       0.99      0.99      0.99     13184

f1 score for validation model is :  0.8830409356725146
-------------------------------------------------------


In [ ]:
# predict testing results

In [96]:
df2.columns == x_test.columns


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [99]:
final1_y_test = rfgrid.predict(df2)

In [100]:
final1_y_test

array([1, 0, 0, ..., 0, 0, 0])

In [101]:
final = pd.DataFrame(final1_y_test)

In [102]:
final.value_counts()

0    12878
1      306
dtype: int64

# Logistic regression
    

In [19]:
# case 1 - base model
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()
log_model.fit(x_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [21]:
# 1. Predict Training Results
y_pred_train = log_model.predict(x_train)
 

In [24]:
# Evaluating model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

print('Training accuracy is', accuracy_score(y_train, y_pred_train)*100)
print('-------------------------------------------------------')
print('Confusion Matrix for training data is \n', confusion_matrix(y_train, y_pred_train))
print('-------------------------------------------------------')
print('Classification report for training data \n', (classification_report(y_train, y_pred_train)))
print('=======================================================')
print("f1 score for base model is : " , f1_score(y_train, y_pred_train))
print('-------------------------------------------------------')


Training accuracy is 97.31550051072523
-------------------------------------------------------
Confusion Matrix for training data is 
 [[29693    37]
 [  804   794]]
-------------------------------------------------------
Classification report for training data 
               precision    recall  f1-score   support

           0       0.97      1.00      0.99     29730
           1       0.96      0.50      0.65      1598

    accuracy                           0.97     31328
   macro avg       0.96      0.75      0.82     31328
weighted avg       0.97      0.97      0.97     31328

f1 score for base model is :  0.6537669822972416
-------------------------------------------------------


In [25]:
# 2. Predict Validation Results
y_pred_val = log_model.predict(x_test)


In [27]:
# evaluation metrics
print('Validation accuracy is', accuracy_score(y_test, y_pred_val))
print('-------------------------------------------------------')
print('Confusion Matrix for Validation data is \n', confusion_matrix(y_test, y_pred_val))
print('-------------------------------------------------------')
print('Classification report for Validation data \n', (classification_report(y_test, y_pred_val)))
print('=======================================================')
print("f1 score for validation model is : " , f1_score(y_test, y_pred_val))
print('-------------------------------------------------------')


Validation accuracy is 0.9737010085535555
-------------------------------------------------------
Confusion Matrix for Validation data is 
 [[7428    5]
 [ 201  199]]
-------------------------------------------------------
Classification report for Validation data 
               precision    recall  f1-score   support

           0       0.97      1.00      0.99      7433
           1       0.98      0.50      0.66       400

    accuracy                           0.97      7833
   macro avg       0.97      0.75      0.82      7833
weighted avg       0.97      0.97      0.97      7833

f1 score for validation model is :  0.6589403973509934
-------------------------------------------------------


In [35]:
# 3. Predict Testing Results -- Unsupervised Data
x_test.columns == df2.columns


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [36]:
log_y_test = log_model.predict(df2)  


In [37]:
log_y_test


array([1, 0, 0, ..., 0, 0, 0])

In [39]:
y_test = pd.DataFrame(log_y_test) 


In [40]:
y_test.value_counts()


0    12907
1      277
dtype: int64

# Case_2 :- Logistic Regression -- Hyperparameter Tuning/Model Improvement


In [57]:
log_model_2 = LogisticRegression(C=1, penalty='l1', solver='liblinear')
log_model_2.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [48]:
param_grid = [
    {'penalty':['l1','l2','elasticnet','none'],
     'C':[100,10,0.1,0.01],
     'solver':['lbfgs','newton-cg','liblinear','sag','saga'],
     'max_iter':[1000]
        
    }   # default [solver=’lbfgs’]
]

In [55]:
from sklearn.model_selection import GridSearchCV

log_grid = GridSearchCV(log_model_2, param_grid=param_grid, cv=2,verbose=True, n_jobs=-1)

Fitting 2 folds for each of 80 candidates, totalling 160 fits


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
72 fits failed out of a total of 160.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver

GridSearchCV(cv=2,
             estimator=LogisticRegression(C=1, penalty='l1',
                                          solver='liblinear'),
             n_jobs=-1,
             param_grid=[{'C': [100, 10, 0.1, 0.01], 'max_iter': [1000],
                          'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                          'solver': ['lbfgs', 'newton-cg', 'liblinear', 'sag',
                                     'saga']}],
             verbose=True)

In [60]:
# 1. Predict Training Results
log_pred_train = log_model_2.predict(x_train)


In [61]:
print('Training accuracy is', accuracy_score(y_train, log_pred_train)*100)
print('-------------------------------------------------------')
print('Confusion Matrix for training data is \n', confusion_matrix(y_train, log_pred_train))
print('-------------------------------------------------------')
print('Classification report for training data \n', (classification_report(y_train, log_pred_train)))
print('=======================================================')
print("f1 score for base model is : " , f1_score(y_train, log_pred_train))
print('-------------------------------------------------------')


Training accuracy is 97.33784473953013
-------------------------------------------------------
Confusion Matrix for training data is 
 [[29690    40]
 [  794   804]]
-------------------------------------------------------
Classification report for training data 
               precision    recall  f1-score   support

           0       0.97      1.00      0.99     29730
           1       0.95      0.50      0.66      1598

    accuracy                           0.97     31328
   macro avg       0.96      0.75      0.82     31328
weighted avg       0.97      0.97      0.97     31328

f1 score for base model is :  0.6584766584766585
-------------------------------------------------------


In [65]:
# 2. Predict Validation Results
y_pred_val = log_model_2.predict(df2)


In [67]:
print('Validation accuracy is', accuracy_score(y_test, y_pred_val))
print('-------------------------------------------------------')
print('Confusion Matrix for Validation data is \n', confusion_matrix(y_test, y_pred_val))
print('-------------------------------------------------------')
print('Classification report for Validation data \n', (classification_report(y_test, y_pred_val)))
print('=======================================================')
print("f1 score for validation model is : " , f1_score(y_test, y_pred_val))
print('-------------------------------------------------------')


Validation accuracy is 0.9995449029126213
-------------------------------------------------------
Confusion Matrix for Validation data is 
 [[12901     6]
 [    0   277]]
-------------------------------------------------------
Classification report for Validation data 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     12907
           1       0.98      1.00      0.99       277

    accuracy                           1.00     13184
   macro avg       0.99      1.00      0.99     13184
weighted avg       1.00      1.00      1.00     13184

f1 score for validation model is :  0.9892857142857143
-------------------------------------------------------


In [68]:
# 3. Predict Testing Results
x_test.columns == df2.columns


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [70]:
log2_y_val = log_model_2.predict(df2)  



In [71]:
log2_y_val

array([1, 0, 0, ..., 0, 0, 0])

In [72]:
y_test = pd.DataFrame(log2_y_val) 


In [73]:
y_test.value_counts()


0    12901
1      283
dtype: int64